#使用方法 cd到项目.xcworkspace目录 终端输入 fastlane automaticPackagingUpload

# 定义fastlane版本号
fastlane_version “2.126.0” 

# 定义打包平台
default_platform :ios

#指定项目的scheme名称
scheme = “ReaseTest”

#蒲公英api_key和user_key
api_key  = “ae814e229dfea7c1e8eb63a6cbcf8928”
user_key = “916875a4fc640d278b8ba8ef43203aa2”


def updateProjectBuildNumber

currentTime = Time.new.strftime("%Y%m%d")
build = get_build_number()
if build.include?"#{currentTime}."
# => 为当天版本 计算迭代版本号
lastStr = build[build.length-2..build.length-1]
lastNum = lastStr.to_i
lastNum = lastNum + 1
lastStr = lastNum.to_s
if lastNum < 10
lastStr = lastStr.insert(0,"0")
end
build = "#{currentTime}.#{lastStr}"
else
# => 非当天版本 build 号重置
build = "#{currentTime}.01"
end
puts("*************| 更新build #{build} |*************")
# => 更改项目 build 号
increment_build_number(
build_number: "#{build}"
)
end


# 任务脚本
platform :ios do
lane :automaticPackagingUpload do|options|
branch = options[:branch]

puts “*************| 开始打包.ipa文件 |*************”

updateProjectBuildNumber #更改项目build号

# 开始打包
gym(
#输出的ipa名称
output_name:”#{scheme}_#{get_build_number()}”,
#指定项目的scheme
scheme:"#{scheme}",
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:"Release",
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"development",
# 指定输出文件夹
output_directory:"~/Desktop/fastlaneBuild",
)

puts “*************| 开始上传蒲公英 |*************”

# 开始上传蒲公英
pgyer(api_key: “#{api_key}”, user_key: “#{user_key}”)

puts “*************| 上传蒲公英成功！|*************”

end
end